import 'package:council/src/services/chat_history_service.dart';
import 'package:council/src/services/user_database.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';

/// Conversations that outlive the app being closed.
void main() {
  late Database db;
  late ChatHistoryService history;

  setUpAll(() {
    sqfliteFfiInit();
    databaseFactory = databaseFactoryFfi;
  });

  setUp(() async {
    db = await databaseFactoryFfi.openDatabase(
      inMemoryDatabasePath,
      options: OpenDatabaseOptions(singleInstance: false),
    );
    await UserDatabase.useForTesting(db);
    history = ChatHistoryService();
  });

  tearDown(() async {
    UserDatabase.resetForTesting();
    await db.close();
  });

  test('messages come back in the order they were sent', () async {
    final conversation = await history.createConversation();
    await history.addMessage(
        conversationId: conversation.id, isUser: true, text: 'What is grace?');
    await history.addMessage(
        conversationId: conversation.id, isUser: false, text: 'Augustine says…');
    await history.addMessage(
        conversationId: conversation.id, isUser: true, text: 'And Aquinas?');

    final messages = await history.messages(conversation.id);
    expect(messages.map((m) => m.text).toList(),
        ['What is grace?', 'Augustine says…', 'And Aquinas?']);
    expect(messages.map((m) => m.isUser).toList(), [true, false, true]);
  });

  test('citations survive the round trip', () async {
    // An answer that comes back without its sources is the thing this app is
    // trying not to be, so they are stored with the message rather than
    // regenerated by asking again.
    final conversation = await history.createConversation();
    await history.addMessage(
      conversationId: conversation.id,
      isUser: false,
      text: 'Grace is prevenient [1].',
      citations: [
        {'contentId': 42, 'source': 'On Grace and Free Will'},
      ],
    );

    final stored = (await history.messages(conversation.id)).single;
    expect(stored.citations.single['source'], 'On Grace and Free Will');
    expect(stored.citations.single['contentId'], 42);
  });

  test('a message records whether a model wrote it', () async {
    // The reliability caveat hangs off this: it belongs under an answer a
    // model produced, not under a retrieval-only result or an error notice
    // the app composed itself.
    final conversation = await history.createConversation();
    await history.addMessage(
        conversationId: conversation.id,
        isUser: false,
        text: 'Search-only mode is on…');
    await history.addMessage(
        conversationId: conversation.id,
        isUser: false,
        text: 'Augustine says…',
        generated: true);

    final messages = await history.messages(conversation.id);
    expect(messages.map((m) => m.generated).toList(), [false, true]);
  });

  test('a malformed citation blob costs the citations, not the message',
      () async {
    final conversation = await history.createConversation();
    final id = await history.addMessage(
        conversationId: conversation.id, isUser: false, text: 'An answer.');
    await db.update('conversation_messages', {'citations': 'not json'},
        where: 'id = ?', whereArgs: [id]);

    final stored = (await history.messages(conversation.id)).single;
    expect(stored.text, 'An answer.');
    expect(stored.citations, isEmpty);
  });

  test('empty conversations stay out of the history list', () async {
    // One is created the moment a reader taps "ask about this passage"; going
    // back without asking anything must not leave a thread behind.
    await history.createConversation();
    expect(await history.conversations(), isEmpty);
  });

  test('the list is ordered by most recent activity', () async {
    final older = await history.createConversation(title: 'older');
    final newer = await history.createConversation(title: 'newer');
    await history.addMessage(
        conversationId: older.id, isUser: true, text: 'first');
    await Future<void>.delayed(const Duration(milliseconds: 5));
    await history.addMessage(
        conversationId: newer.id, isUser: true, text: 'second');

    expect((await history.conversations()).map((c) => c.title).toList(),
        ['newer', 'older']);

    // Returning to the older thread lifts it back to the top.
    await Future<void>.delayed(const Duration(milliseconds: 5));
    await history.addMessage(
        conversationId: older.id, isUser: true, text: 'again');
    expect((await history.conversations()).first.title, 'older');
  });

  test('the list carries a preview and a count', () async {
    final conversation = await history.createConversation();
    await history.addMessage(
        conversationId: conversation.id, isUser: true, text: 'question');
    await history.addMessage(
        conversationId: conversation.id, isUser: false, text: 'answer');

    final listed = (await history.conversations()).single;
    expect(listed.messageCount, 2);
    expect(listed.preview, 'answer');
  });

  test('a thread is named after its opening question, once', () async {
    final conversation = await history.createConversation();
    await history.retitleIfUnnamed(conversation.id, 'What did Trent decree?');
    await history.retitleIfUnnamed(conversation.id, 'Something else entirely');

    final stored = await history.conversation(conversation.id);
    expect(stored!.title, 'What did Trent decree?');
  });

  test('a passage-anchored thread remembers its passage', () async {
    const passage = PinnedPassage(
      contentUnitId: 23558,
      quote: 'In the beginning God created the heaven and the earth.',
      reference: 'Genesis 1:1',
      sourceTitle: 'The Holy Bible: King James Version',
    );
    final conversation =
        await history.createConversation(title: 'Genesis 1:1', passage: passage);

    final stored = await history.conversation(conversation.id);
    expect(stored!.passage!.contentUnitId, 23558);
    expect(stored.passage!.reference, 'Genesis 1:1');
    expect(stored.passage!.quote, startsWith('In the beginning'));
  });

  test('deleting a conversation takes its messages with it', () async {
    final conversation = await history.createConversation();
    await history.addMessage(
        conversationId: conversation.id, isUser: true, text: 'hello');
    await history.deleteConversation(conversation.id);

    expect(await history.conversation(conversation.id), isNull);
    expect(await history.messages(conversation.id), isEmpty);
  });

  test('deleteIfEmpty spares a thread that was used', () async {
    final used = await history.createConversation();
    await history.addMessage(
        conversationId: used.id, isUser: true, text: 'hello');
    final unused = await history.createConversation();

    await history.deleteIfEmpty(used.id);
    await history.deleteIfEmpty(unused.id);

    expect(await history.conversation(used.id), isNotNull);
    expect(await history.conversation(unused.id), isNull);
  });
}
